name: vt_polyglot
description: A multilingual learning app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dropdown_search: ^5.0.6
  shared_preferences: ^2.2.2
  http: ^1.5.0
  google_generative_ai: ^0.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^8.0.0
  flutter_tts: ^4.2.3
  flutter_sound: ^9.28.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  record: ^6.1.2
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true